version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file template.yaml --s3-bucket sam-app-sample --output-template-file packaged-template.yaml
      - pipenv run aws cloudformation deploy --template-file $CODEBUILD_SRC_DIR/packaged-template.yaml --stack-name HelloServerLess
artifacts:
  files:
    - packaged-template.yaml
